openapi: 3.0.0
info:
  title: homeflix API
  description: Homeflix service is an API that provides access to a database of information about movies, series and animes.
  version: 1.0.0
# Second part
servers:
  - url: http://localhost:5000
    description: Local developement server
paths:
  /medias/{media_id}:
    get:
      summary: Return a media by id.
      operationId: src.medias.media_by_id
      parameters:
        - in: path
          name: media_id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The media ID
      responses:
        '200': # movie found
          description: A media json object
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
        '400':
          description: Bad request. Media ID must be an integer and larger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A media with the specified ID was not found.
        '5XX':
          description: Unexpected error.
  /medias:
    get:
      summary: Return a list of media objects based on media type provided.
      operationId: src.medias.medias_by_type
      parameters:
        - in: query
          name: media_type
          schema:
            type: string
            enum:
              - all
              - movies
              - series
              - animes
            default: all
          description: The type of medias to returns
      responses:
        '200': # status code
          description: A json array of media objects
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Media'
        '400':
          description: Bad request. Media ID must be an integer and larger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A media with the specified ID was not found.
        '5XX':
          description: Unexpected error.
  /medias/search:
    get:
      summary: Return a list of search on media titles results, results are media objects.
      operationId: src.medias.search
      parameters:
        - in: query
          name: title
          schema:
            type: string
          description: The title of media to search
      responses:
        '200': # status code
          description: A json array of media objects
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Media'
        '400':
          description: Bad request. Media ID must be an integer and larger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A media with the specified ID was not found.
        '5XX':
          description: Unexpected error.

components:
  schemas:
    Rating:
      type: object
      properties:
        source:
          type: string
          example: 'Rotten Tomatoes'
        value: 
          type: string
          example: '94%'

    Media:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: 'The Dark Knight'
        rated:
          type: string
          example: 'PG-13'
        year: 
          type: integer
          example: 2008
        released:
          type: string
          example: '18 Jul 2008'
        runtime:
          type: string
          example: '152 min'
        genre: 
          type: string
          example: 'Action, Crime, Drama, Thriller'
        director:
          type: string
          example: 'Christopher Nolan'
        writer:
          type: string
          example: 'Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)'
        actors:
          type: string
          example: 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine'
        plot:
          type: string
          example: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.'
        language:
          type: string
          example: 'English, Mandarin'
        country:
          type: string
          example: 'USA, UK'
        awards:
          type: string
          example: 'Won 2 Oscars. Another 153 wins & 160 nominations.'
        poster:
          type: string
          example: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg'
        ratings:
          type: array
          items:
            $ref: '#/components/schemas/Rating'
        imdbRating:
          type: number
          example: 9.0
        mediaType:
          type: string
          enum:
            - movies
            - series
            - animes